// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/billing/billing.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.billing;

/**
 * <pre>
 * ExceededAllowance is an allowance the environment is already over after a plan change.
 * </pre>
 *
 * Protobuf type {@code scalekit.v1.billing.ExceededAllowance}
 */
public final class ExceededAllowance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.billing.ExceededAllowance)
    ExceededAllowanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExceededAllowance.newBuilder() to construct.
  private ExceededAllowance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExceededAllowance() {
    entitlement_ = "";
    line_ = "";
    onExceed_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExceededAllowance();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.billing.BillingProto.internal_static_scalekit_v1_billing_ExceededAllowance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.billing.BillingProto.internal_static_scalekit_v1_billing_ExceededAllowance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.class, com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.Builder.class);
  }

  public static final int ENTITLEMENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entitlement_ = "";
  /**
   * <code>string entitlement = 1 [json_name = "entitlement"];</code>
   * @return The entitlement.
   */
  @java.lang.Override
  public java.lang.String getEntitlement() {
    java.lang.Object ref = entitlement_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entitlement_ = s;
      return s;
    }
  }
  /**
   * <code>string entitlement = 1 [json_name = "entitlement"];</code>
   * @return The bytes for entitlement.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntitlementBytes() {
    java.lang.Object ref = entitlement_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entitlement_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object line_ = "";
  /**
   * <code>string line = 2 [json_name = "line"];</code>
   * @return The line.
   */
  @java.lang.Override
  public java.lang.String getLine() {
    java.lang.Object ref = line_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      line_ = s;
      return s;
    }
  }
  /**
   * <code>string line = 2 [json_name = "line"];</code>
   * @return The bytes for line.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLineBytes() {
    java.lang.Object ref = line_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      line_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOWANCE_FIELD_NUMBER = 3;
  private long allowance_ = 0L;
  /**
   * <code>int64 allowance = 3 [json_name = "allowance"];</code>
   * @return The allowance.
   */
  @java.lang.Override
  public long getAllowance() {
    return allowance_;
  }

  public static final int CURRENT_USAGE_FIELD_NUMBER = 4;
  private long currentUsage_ = 0L;
  /**
   * <code>int64 current_usage = 4 [json_name = "currentUsage"];</code>
   * @return The currentUsage.
   */
  @java.lang.Override
  public long getCurrentUsage() {
    return currentUsage_;
  }

  public static final int ON_EXCEED_FIELD_NUMBER = 5;
  private int onExceed_ = 0;
  /**
   * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
   * @return The enum numeric value on the wire for onExceed.
   */
  @java.lang.Override public int getOnExceedValue() {
    return onExceed_;
  }
  /**
   * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
   * @return The onExceed.
   */
  @java.lang.Override public com.scalekit.grpc.scalekit.v1.billing.OnExceed getOnExceed() {
    com.scalekit.grpc.scalekit.v1.billing.OnExceed result = com.scalekit.grpc.scalekit.v1.billing.OnExceed.forNumber(onExceed_);
    return result == null ? com.scalekit.grpc.scalekit.v1.billing.OnExceed.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entitlement_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, entitlement_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, line_);
    }
    if (allowance_ != 0L) {
      output.writeInt64(3, allowance_);
    }
    if (currentUsage_ != 0L) {
      output.writeInt64(4, currentUsage_);
    }
    if (onExceed_ != com.scalekit.grpc.scalekit.v1.billing.OnExceed.ON_EXCEED_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, onExceed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(entitlement_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, entitlement_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(line_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, line_);
    }
    if (allowance_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, allowance_);
    }
    if (currentUsage_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, currentUsage_);
    }
    if (onExceed_ != com.scalekit.grpc.scalekit.v1.billing.OnExceed.ON_EXCEED_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, onExceed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance other = (com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance) obj;

    if (!getEntitlement()
        .equals(other.getEntitlement())) return false;
    if (!getLine()
        .equals(other.getLine())) return false;
    if (getAllowance()
        != other.getAllowance()) return false;
    if (getCurrentUsage()
        != other.getCurrentUsage()) return false;
    if (onExceed_ != other.onExceed_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENTITLEMENT_FIELD_NUMBER;
    hash = (53 * hash) + getEntitlement().hashCode();
    hash = (37 * hash) + LINE_FIELD_NUMBER;
    hash = (53 * hash) + getLine().hashCode();
    hash = (37 * hash) + ALLOWANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAllowance());
    hash = (37 * hash) + CURRENT_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentUsage());
    hash = (37 * hash) + ON_EXCEED_FIELD_NUMBER;
    hash = (53 * hash) + onExceed_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ExceededAllowance is an allowance the environment is already over after a plan change.
   * </pre>
   *
   * Protobuf type {@code scalekit.v1.billing.ExceededAllowance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.billing.ExceededAllowance)
      com.scalekit.grpc.scalekit.v1.billing.ExceededAllowanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.billing.BillingProto.internal_static_scalekit_v1_billing_ExceededAllowance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.billing.BillingProto.internal_static_scalekit_v1_billing_ExceededAllowance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.class, com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      entitlement_ = "";
      line_ = "";
      allowance_ = 0L;
      currentUsage_ = 0L;
      onExceed_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.billing.BillingProto.internal_static_scalekit_v1_billing_ExceededAllowance_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance build() {
      com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance buildPartial() {
      com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance result = new com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.entitlement_ = entitlement_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.line_ = line_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.allowance_ = allowance_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.currentUsage_ = currentUsage_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.onExceed_ = onExceed_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance other) {
      if (other == com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance.getDefaultInstance()) return this;
      if (!other.getEntitlement().isEmpty()) {
        entitlement_ = other.entitlement_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLine().isEmpty()) {
        line_ = other.line_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAllowance() != 0L) {
        setAllowance(other.getAllowance());
      }
      if (other.getCurrentUsage() != 0L) {
        setCurrentUsage(other.getCurrentUsage());
      }
      if (other.onExceed_ != 0) {
        setOnExceedValue(other.getOnExceedValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              entitlement_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              line_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              allowance_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              currentUsage_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              onExceed_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object entitlement_ = "";
    /**
     * <code>string entitlement = 1 [json_name = "entitlement"];</code>
     * @return The entitlement.
     */
    public java.lang.String getEntitlement() {
      java.lang.Object ref = entitlement_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entitlement_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entitlement = 1 [json_name = "entitlement"];</code>
     * @return The bytes for entitlement.
     */
    public com.google.protobuf.ByteString
        getEntitlementBytes() {
      java.lang.Object ref = entitlement_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entitlement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entitlement = 1 [json_name = "entitlement"];</code>
     * @param value The entitlement to set.
     * @return This builder for chaining.
     */
    public Builder setEntitlement(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entitlement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string entitlement = 1 [json_name = "entitlement"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEntitlement() {
      entitlement_ = getDefaultInstance().getEntitlement();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string entitlement = 1 [json_name = "entitlement"];</code>
     * @param value The bytes for entitlement to set.
     * @return This builder for chaining.
     */
    public Builder setEntitlementBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entitlement_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object line_ = "";
    /**
     * <code>string line = 2 [json_name = "line"];</code>
     * @return The line.
     */
    public java.lang.String getLine() {
      java.lang.Object ref = line_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        line_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string line = 2 [json_name = "line"];</code>
     * @return The bytes for line.
     */
    public com.google.protobuf.ByteString
        getLineBytes() {
      java.lang.Object ref = line_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        line_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string line = 2 [json_name = "line"];</code>
     * @param value The line to set.
     * @return This builder for chaining.
     */
    public Builder setLine(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      line_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string line = 2 [json_name = "line"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLine() {
      line_ = getDefaultInstance().getLine();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string line = 2 [json_name = "line"];</code>
     * @param value The bytes for line to set.
     * @return This builder for chaining.
     */
    public Builder setLineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      line_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long allowance_ ;
    /**
     * <code>int64 allowance = 3 [json_name = "allowance"];</code>
     * @return The allowance.
     */
    @java.lang.Override
    public long getAllowance() {
      return allowance_;
    }
    /**
     * <code>int64 allowance = 3 [json_name = "allowance"];</code>
     * @param value The allowance to set.
     * @return This builder for chaining.
     */
    public Builder setAllowance(long value) {

      allowance_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 allowance = 3 [json_name = "allowance"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowance() {
      bitField0_ = (bitField0_ & ~0x00000004);
      allowance_ = 0L;
      onChanged();
      return this;
    }

    private long currentUsage_ ;
    /**
     * <code>int64 current_usage = 4 [json_name = "currentUsage"];</code>
     * @return The currentUsage.
     */
    @java.lang.Override
    public long getCurrentUsage() {
      return currentUsage_;
    }
    /**
     * <code>int64 current_usage = 4 [json_name = "currentUsage"];</code>
     * @param value The currentUsage to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentUsage(long value) {

      currentUsage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 current_usage = 4 [json_name = "currentUsage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentUsage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      currentUsage_ = 0L;
      onChanged();
      return this;
    }

    private int onExceed_ = 0;
    /**
     * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
     * @return The enum numeric value on the wire for onExceed.
     */
    @java.lang.Override public int getOnExceedValue() {
      return onExceed_;
    }
    /**
     * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
     * @param value The enum numeric value on the wire for onExceed to set.
     * @return This builder for chaining.
     */
    public Builder setOnExceedValue(int value) {
      onExceed_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
     * @return The onExceed.
     */
    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.billing.OnExceed getOnExceed() {
      com.scalekit.grpc.scalekit.v1.billing.OnExceed result = com.scalekit.grpc.scalekit.v1.billing.OnExceed.forNumber(onExceed_);
      return result == null ? com.scalekit.grpc.scalekit.v1.billing.OnExceed.UNRECOGNIZED : result;
    }
    /**
     * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
     * @param value The onExceed to set.
     * @return This builder for chaining.
     */
    public Builder setOnExceed(com.scalekit.grpc.scalekit.v1.billing.OnExceed value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      onExceed_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.scalekit.v1.billing.OnExceed on_exceed = 5 [json_name = "onExceed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOnExceed() {
      bitField0_ = (bitField0_ & ~0x00000010);
      onExceed_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.billing.ExceededAllowance)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.billing.ExceededAllowance)
  private static final com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance();
  }

  public static com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExceededAllowance>
      PARSER = new com.google.protobuf.AbstractParser<ExceededAllowance>() {
    @java.lang.Override
    public ExceededAllowance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExceededAllowance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExceededAllowance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.billing.ExceededAllowance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

