// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/gateway/gateway.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.gateway;

/**
 * Protobuf type {@code scalekit.v1.gateway.ListGatewayGroupsRequest}
 */
public final class ListGatewayGroupsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.gateway.ListGatewayGroupsRequest)
    ListGatewayGroupsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListGatewayGroupsRequest.newBuilder() to construct.
  private ListGatewayGroupsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListGatewayGroupsRequest() {
    source_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListGatewayGroupsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.gateway.GatewayProto.internal_static_scalekit_v1_gateway_ListGatewayGroupsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.gateway.GatewayProto.internal_static_scalekit_v1_gateway_ListGatewayGroupsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.class, com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private int source_ = 0;
  /**
   * <pre>
   * Optional source filter — return only groups of this source. When
   * SOURCE_UNSPECIFIED, every source is returned.
   * </pre>
   *
   * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
   * @return The enum numeric value on the wire for source.
   */
  @java.lang.Override public int getSourceValue() {
    return source_;
  }
  /**
   * <pre>
   * Optional source filter — return only groups of this source. When
   * SOURCE_UNSPECIFIED, every source is returned.
   * </pre>
   *
   * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
   * @return The source.
   */
  @java.lang.Override public com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource getSource() {
    com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource result = com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.forNumber(source_);
    return result == null ? com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (source_ != com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.GATEWAY_GROUP_SOURCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, source_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (source_ != com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.GATEWAY_GROUP_SOURCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, source_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest other = (com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest) obj;

    if (source_ != other.source_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + source_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scalekit.v1.gateway.ListGatewayGroupsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.gateway.ListGatewayGroupsRequest)
      com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.gateway.GatewayProto.internal_static_scalekit_v1_gateway_ListGatewayGroupsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.gateway.GatewayProto.internal_static_scalekit_v1_gateway_ListGatewayGroupsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.class, com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      source_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.gateway.GatewayProto.internal_static_scalekit_v1_gateway_ListGatewayGroupsRequest_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest build() {
      com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest buildPartial() {
      com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest result = new com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.source_ = source_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest other) {
      if (other == com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest.getDefaultInstance()) return this;
      if (other.source_ != 0) {
        setSourceValue(other.getSourceValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              source_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int source_ = 0;
    /**
     * <pre>
     * Optional source filter — return only groups of this source. When
     * SOURCE_UNSPECIFIED, every source is returned.
     * </pre>
     *
     * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
     * @return The enum numeric value on the wire for source.
     */
    @java.lang.Override public int getSourceValue() {
      return source_;
    }
    /**
     * <pre>
     * Optional source filter — return only groups of this source. When
     * SOURCE_UNSPECIFIED, every source is returned.
     * </pre>
     *
     * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
     * @param value The enum numeric value on the wire for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceValue(int value) {
      source_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional source filter — return only groups of this source. When
     * SOURCE_UNSPECIFIED, every source is returned.
     * </pre>
     *
     * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
     * @return The source.
     */
    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource getSource() {
      com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource result = com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.forNumber(source_);
      return result == null ? com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Optional source filter — return only groups of this source. When
     * SOURCE_UNSPECIFIED, every source is returned.
     * </pre>
     *
     * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(com.scalekit.grpc.scalekit.v1.gateway.GatewayGroupSource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      source_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional source filter — return only groups of this source. When
     * SOURCE_UNSPECIFIED, every source is returned.
     * </pre>
     *
     * <code>.scalekit.v1.gateway.GatewayGroupSource source = 1 [json_name = "source"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      bitField0_ = (bitField0_ & ~0x00000001);
      source_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.gateway.ListGatewayGroupsRequest)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.gateway.ListGatewayGroupsRequest)
  private static final com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest();
  }

  public static com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListGatewayGroupsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListGatewayGroupsRequest>() {
    @java.lang.Override
    public ListGatewayGroupsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListGatewayGroupsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListGatewayGroupsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.gateway.ListGatewayGroupsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

