// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/environments/environments.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.environments;

/**
 * Protobuf enum {@code scalekit.v1.environments.OrgUserRelationshipType}
 */
public enum OrgUserRelationshipType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OrgUserRelationshipType_UNSPECIFIED = 0;</code>
   */
  OrgUserRelationshipType_UNSPECIFIED(0),
  /**
   * <code>SINGLE_ORGANIZATION = 1;</code>
   */
  SINGLE_ORGANIZATION(1),
  /**
   * <code>MULTIPLE_ORGANIZATIONS = 2;</code>
   */
  MULTIPLE_ORGANIZATIONS(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OrgUserRelationshipType_UNSPECIFIED = 0;</code>
   */
  public static final int OrgUserRelationshipType_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SINGLE_ORGANIZATION = 1;</code>
   */
  public static final int SINGLE_ORGANIZATION_VALUE = 1;
  /**
   * <code>MULTIPLE_ORGANIZATIONS = 2;</code>
   */
  public static final int MULTIPLE_ORGANIZATIONS_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OrgUserRelationshipType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OrgUserRelationshipType forNumber(int value) {
    switch (value) {
      case 0: return OrgUserRelationshipType_UNSPECIFIED;
      case 1: return SINGLE_ORGANIZATION;
      case 2: return MULTIPLE_ORGANIZATIONS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrgUserRelationshipType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OrgUserRelationshipType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrgUserRelationshipType>() {
          public OrgUserRelationshipType findValueByNumber(int number) {
            return OrgUserRelationshipType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.environments.EnvironmentsProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final OrgUserRelationshipType[] VALUES = values();

  public static OrgUserRelationshipType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OrgUserRelationshipType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:scalekit.v1.environments.OrgUserRelationshipType)
}

