// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/users/users.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.users;

public interface AssignUserRolesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scalekit.v1.users.AssignUserRolesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string organization_id = 1 [json_name = "organizationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The organizationId.
   */
  java.lang.String getOrganizationId();
  /**
   * <code>string organization_id = 1 [json_name = "organizationId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for organizationId.
   */
  com.google.protobuf.ByteString
      getOrganizationIdBytes();

  /**
   * <code>string user_id = 2 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2 [json_name = "userId", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .scalekit.v1.users.AssignRoleRequest roles = 3 [json_name = "roles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  java.util.List<com.scalekit.grpc.scalekit.v1.users.AssignRoleRequest> 
      getRolesList();
  /**
   * <code>repeated .scalekit.v1.users.AssignRoleRequest roles = 3 [json_name = "roles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  com.scalekit.grpc.scalekit.v1.users.AssignRoleRequest getRoles(int index);
  /**
   * <code>repeated .scalekit.v1.users.AssignRoleRequest roles = 3 [json_name = "roles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  int getRolesCount();
  /**
   * <code>repeated .scalekit.v1.users.AssignRoleRequest roles = 3 [json_name = "roles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  java.util.List<? extends com.scalekit.grpc.scalekit.v1.users.AssignRoleRequestOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <code>repeated .scalekit.v1.users.AssignRoleRequest roles = 3 [json_name = "roles", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  com.scalekit.grpc.scalekit.v1.users.AssignRoleRequestOrBuilder getRolesOrBuilder(
      int index);
}
