// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/connections/connections.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.connections;

/**
 * Protobuf type {@code scalekit.v1.connections.GetSAMLMetadataResponse}
 */
public final class GetSAMLMetadataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.connections.GetSAMLMetadataResponse)
    GetSAMLMetadataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSAMLMetadataResponse.newBuilder() to construct.
  private GetSAMLMetadataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSAMLMetadataResponse() {
    idpEntityId_ = "";
    idpSsoUrl_ = "";
    idpSloUrl_ = "";
    idpCertificates_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    idpNameIdFormat_ = "";
    requestBinding_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSAMLMetadataResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.connections.ConnectionsProto.internal_static_scalekit_v1_connections_GetSAMLMetadataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.connections.ConnectionsProto.internal_static_scalekit_v1_connections_GetSAMLMetadataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.class, com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.Builder.class);
  }

  public static final int IDP_ENTITY_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idpEntityId_ = "";
  /**
   * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
   * @return The idpEntityId.
   */
  @java.lang.Override
  public java.lang.String getIdpEntityId() {
    java.lang.Object ref = idpEntityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idpEntityId_ = s;
      return s;
    }
  }
  /**
   * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
   * @return The bytes for idpEntityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdpEntityIdBytes() {
    java.lang.Object ref = idpEntityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idpEntityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDP_SSO_URL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idpSsoUrl_ = "";
  /**
   * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
   * @return The idpSsoUrl.
   */
  @java.lang.Override
  public java.lang.String getIdpSsoUrl() {
    java.lang.Object ref = idpSsoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idpSsoUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
   * @return The bytes for idpSsoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdpSsoUrlBytes() {
    java.lang.Object ref = idpSsoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idpSsoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDP_SLO_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idpSloUrl_ = "";
  /**
   * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
   * @return The idpSloUrl.
   */
  @java.lang.Override
  public java.lang.String getIdpSloUrl() {
    java.lang.Object ref = idpSloUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idpSloUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
   * @return The bytes for idpSloUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdpSloUrlBytes() {
    java.lang.Object ref = idpSloUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idpSloUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDP_CERTIFICATES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList idpCertificates_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
   * @return A list containing the idpCertificates.
   */
  public com.google.protobuf.ProtocolStringList
      getIdpCertificatesList() {
    return idpCertificates_;
  }
  /**
   * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
   * @return The count of idpCertificates.
   */
  public int getIdpCertificatesCount() {
    return idpCertificates_.size();
  }
  /**
   * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
   * @param index The index of the element to return.
   * @return The idpCertificates at the given index.
   */
  public java.lang.String getIdpCertificates(int index) {
    return idpCertificates_.get(index);
  }
  /**
   * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the idpCertificates at the given index.
   */
  public com.google.protobuf.ByteString
      getIdpCertificatesBytes(int index) {
    return idpCertificates_.getByteString(index);
  }

  public static final int IDP_NAME_ID_FORMAT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idpNameIdFormat_ = "";
  /**
   * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
   * @return The idpNameIdFormat.
   */
  @java.lang.Override
  public java.lang.String getIdpNameIdFormat() {
    java.lang.Object ref = idpNameIdFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idpNameIdFormat_ = s;
      return s;
    }
  }
  /**
   * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
   * @return The bytes for idpNameIdFormat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdpNameIdFormatBytes() {
    java.lang.Object ref = idpNameIdFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idpNameIdFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_BINDING_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestBinding_ = "";
  /**
   * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
   * @return The requestBinding.
   */
  @java.lang.Override
  public java.lang.String getRequestBinding() {
    java.lang.Object ref = requestBinding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestBinding_ = s;
      return s;
    }
  }
  /**
   * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
   * @return The bytes for requestBinding.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestBindingBytes() {
    java.lang.Object ref = requestBinding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestBinding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WANT_ASSERTIONS_SIGNED_FIELD_NUMBER = 7;
  private boolean wantAssertionsSigned_ = false;
  /**
   * <code>bool want_assertions_signed = 7 [json_name = "wantAssertionsSigned"];</code>
   * @return The wantAssertionsSigned.
   */
  @java.lang.Override
  public boolean getWantAssertionsSigned() {
    return wantAssertionsSigned_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpEntityId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, idpEntityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpSsoUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idpSsoUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpSloUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, idpSloUrl_);
    }
    for (int i = 0; i < idpCertificates_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, idpCertificates_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpNameIdFormat_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, idpNameIdFormat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestBinding_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requestBinding_);
    }
    if (wantAssertionsSigned_ != false) {
      output.writeBool(7, wantAssertionsSigned_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpEntityId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, idpEntityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpSsoUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idpSsoUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpSloUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, idpSloUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < idpCertificates_.size(); i++) {
        dataSize += computeStringSizeNoTag(idpCertificates_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdpCertificatesList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idpNameIdFormat_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, idpNameIdFormat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestBinding_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requestBinding_);
    }
    if (wantAssertionsSigned_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, wantAssertionsSigned_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse other = (com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse) obj;

    if (!getIdpEntityId()
        .equals(other.getIdpEntityId())) return false;
    if (!getIdpSsoUrl()
        .equals(other.getIdpSsoUrl())) return false;
    if (!getIdpSloUrl()
        .equals(other.getIdpSloUrl())) return false;
    if (!getIdpCertificatesList()
        .equals(other.getIdpCertificatesList())) return false;
    if (!getIdpNameIdFormat()
        .equals(other.getIdpNameIdFormat())) return false;
    if (!getRequestBinding()
        .equals(other.getRequestBinding())) return false;
    if (getWantAssertionsSigned()
        != other.getWantAssertionsSigned()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDP_ENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIdpEntityId().hashCode();
    hash = (37 * hash) + IDP_SSO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getIdpSsoUrl().hashCode();
    hash = (37 * hash) + IDP_SLO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getIdpSloUrl().hashCode();
    if (getIdpCertificatesCount() > 0) {
      hash = (37 * hash) + IDP_CERTIFICATES_FIELD_NUMBER;
      hash = (53 * hash) + getIdpCertificatesList().hashCode();
    }
    hash = (37 * hash) + IDP_NAME_ID_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getIdpNameIdFormat().hashCode();
    hash = (37 * hash) + REQUEST_BINDING_FIELD_NUMBER;
    hash = (53 * hash) + getRequestBinding().hashCode();
    hash = (37 * hash) + WANT_ASSERTIONS_SIGNED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWantAssertionsSigned());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scalekit.v1.connections.GetSAMLMetadataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.connections.GetSAMLMetadataResponse)
      com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.connections.ConnectionsProto.internal_static_scalekit_v1_connections_GetSAMLMetadataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.connections.ConnectionsProto.internal_static_scalekit_v1_connections_GetSAMLMetadataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.class, com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idpEntityId_ = "";
      idpSsoUrl_ = "";
      idpSloUrl_ = "";
      idpCertificates_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      idpNameIdFormat_ = "";
      requestBinding_ = "";
      wantAssertionsSigned_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.connections.ConnectionsProto.internal_static_scalekit_v1_connections_GetSAMLMetadataResponse_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse build() {
      com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse buildPartial() {
      com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse result = new com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idpEntityId_ = idpEntityId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idpSsoUrl_ = idpSsoUrl_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idpSloUrl_ = idpSloUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        idpCertificates_.makeImmutable();
        result.idpCertificates_ = idpCertificates_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.idpNameIdFormat_ = idpNameIdFormat_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.requestBinding_ = requestBinding_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.wantAssertionsSigned_ = wantAssertionsSigned_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse other) {
      if (other == com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse.getDefaultInstance()) return this;
      if (!other.getIdpEntityId().isEmpty()) {
        idpEntityId_ = other.idpEntityId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIdpSsoUrl().isEmpty()) {
        idpSsoUrl_ = other.idpSsoUrl_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getIdpSloUrl().isEmpty()) {
        idpSloUrl_ = other.idpSloUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.idpCertificates_.isEmpty()) {
        if (idpCertificates_.isEmpty()) {
          idpCertificates_ = other.idpCertificates_;
          bitField0_ |= 0x00000008;
        } else {
          ensureIdpCertificatesIsMutable();
          idpCertificates_.addAll(other.idpCertificates_);
        }
        onChanged();
      }
      if (!other.getIdpNameIdFormat().isEmpty()) {
        idpNameIdFormat_ = other.idpNameIdFormat_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getRequestBinding().isEmpty()) {
        requestBinding_ = other.requestBinding_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getWantAssertionsSigned() != false) {
        setWantAssertionsSigned(other.getWantAssertionsSigned());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              idpEntityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              idpSsoUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              idpSloUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureIdpCertificatesIsMutable();
              idpCertificates_.add(s);
              break;
            } // case 34
            case 42: {
              idpNameIdFormat_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              requestBinding_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              wantAssertionsSigned_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object idpEntityId_ = "";
    /**
     * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
     * @return The idpEntityId.
     */
    public java.lang.String getIdpEntityId() {
      java.lang.Object ref = idpEntityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idpEntityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
     * @return The bytes for idpEntityId.
     */
    public com.google.protobuf.ByteString
        getIdpEntityIdBytes() {
      java.lang.Object ref = idpEntityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idpEntityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
     * @param value The idpEntityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdpEntityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idpEntityId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdpEntityId() {
      idpEntityId_ = getDefaultInstance().getIdpEntityId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string idp_entity_id = 1 [json_name = "idpEntityId"];</code>
     * @param value The bytes for idpEntityId to set.
     * @return This builder for chaining.
     */
    public Builder setIdpEntityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idpEntityId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object idpSsoUrl_ = "";
    /**
     * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
     * @return The idpSsoUrl.
     */
    public java.lang.String getIdpSsoUrl() {
      java.lang.Object ref = idpSsoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idpSsoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
     * @return The bytes for idpSsoUrl.
     */
    public com.google.protobuf.ByteString
        getIdpSsoUrlBytes() {
      java.lang.Object ref = idpSsoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idpSsoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
     * @param value The idpSsoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIdpSsoUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idpSsoUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdpSsoUrl() {
      idpSsoUrl_ = getDefaultInstance().getIdpSsoUrl();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string idp_sso_url = 2 [json_name = "idpSsoUrl"];</code>
     * @param value The bytes for idpSsoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIdpSsoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idpSsoUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object idpSloUrl_ = "";
    /**
     * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
     * @return The idpSloUrl.
     */
    public java.lang.String getIdpSloUrl() {
      java.lang.Object ref = idpSloUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idpSloUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
     * @return The bytes for idpSloUrl.
     */
    public com.google.protobuf.ByteString
        getIdpSloUrlBytes() {
      java.lang.Object ref = idpSloUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idpSloUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
     * @param value The idpSloUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIdpSloUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idpSloUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdpSloUrl() {
      idpSloUrl_ = getDefaultInstance().getIdpSloUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string idp_slo_url = 3 [json_name = "idpSloUrl"];</code>
     * @param value The bytes for idpSloUrl to set.
     * @return This builder for chaining.
     */
    public Builder setIdpSloUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idpSloUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList idpCertificates_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureIdpCertificatesIsMutable() {
      if (!idpCertificates_.isModifiable()) {
        idpCertificates_ = new com.google.protobuf.LazyStringArrayList(idpCertificates_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @return A list containing the idpCertificates.
     */
    public com.google.protobuf.ProtocolStringList
        getIdpCertificatesList() {
      idpCertificates_.makeImmutable();
      return idpCertificates_;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @return The count of idpCertificates.
     */
    public int getIdpCertificatesCount() {
      return idpCertificates_.size();
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param index The index of the element to return.
     * @return The idpCertificates at the given index.
     */
    public java.lang.String getIdpCertificates(int index) {
      return idpCertificates_.get(index);
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the idpCertificates at the given index.
     */
    public com.google.protobuf.ByteString
        getIdpCertificatesBytes(int index) {
      return idpCertificates_.getByteString(index);
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param index The index to set the value at.
     * @param value The idpCertificates to set.
     * @return This builder for chaining.
     */
    public Builder setIdpCertificates(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIdpCertificatesIsMutable();
      idpCertificates_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param value The idpCertificates to add.
     * @return This builder for chaining.
     */
    public Builder addIdpCertificates(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureIdpCertificatesIsMutable();
      idpCertificates_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param values The idpCertificates to add.
     * @return This builder for chaining.
     */
    public Builder addAllIdpCertificates(
        java.lang.Iterable<java.lang.String> values) {
      ensureIdpCertificatesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, idpCertificates_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdpCertificates() {
      idpCertificates_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string idp_certificates = 4 [json_name = "idpCertificates"];</code>
     * @param value The bytes of the idpCertificates to add.
     * @return This builder for chaining.
     */
    public Builder addIdpCertificatesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureIdpCertificatesIsMutable();
      idpCertificates_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object idpNameIdFormat_ = "";
    /**
     * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
     * @return The idpNameIdFormat.
     */
    public java.lang.String getIdpNameIdFormat() {
      java.lang.Object ref = idpNameIdFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idpNameIdFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
     * @return The bytes for idpNameIdFormat.
     */
    public com.google.protobuf.ByteString
        getIdpNameIdFormatBytes() {
      java.lang.Object ref = idpNameIdFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idpNameIdFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
     * @param value The idpNameIdFormat to set.
     * @return This builder for chaining.
     */
    public Builder setIdpNameIdFormat(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idpNameIdFormat_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIdpNameIdFormat() {
      idpNameIdFormat_ = getDefaultInstance().getIdpNameIdFormat();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string idp_name_id_format = 5 [json_name = "idpNameIdFormat"];</code>
     * @param value The bytes for idpNameIdFormat to set.
     * @return This builder for chaining.
     */
    public Builder setIdpNameIdFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idpNameIdFormat_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object requestBinding_ = "";
    /**
     * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
     * @return The requestBinding.
     */
    public java.lang.String getRequestBinding() {
      java.lang.Object ref = requestBinding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestBinding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
     * @return The bytes for requestBinding.
     */
    public com.google.protobuf.ByteString
        getRequestBindingBytes() {
      java.lang.Object ref = requestBinding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestBinding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
     * @param value The requestBinding to set.
     * @return This builder for chaining.
     */
    public Builder setRequestBinding(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestBinding_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestBinding() {
      requestBinding_ = getDefaultInstance().getRequestBinding();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string request_binding = 6 [json_name = "requestBinding"];</code>
     * @param value The bytes for requestBinding to set.
     * @return This builder for chaining.
     */
    public Builder setRequestBindingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestBinding_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean wantAssertionsSigned_ ;
    /**
     * <code>bool want_assertions_signed = 7 [json_name = "wantAssertionsSigned"];</code>
     * @return The wantAssertionsSigned.
     */
    @java.lang.Override
    public boolean getWantAssertionsSigned() {
      return wantAssertionsSigned_;
    }
    /**
     * <code>bool want_assertions_signed = 7 [json_name = "wantAssertionsSigned"];</code>
     * @param value The wantAssertionsSigned to set.
     * @return This builder for chaining.
     */
    public Builder setWantAssertionsSigned(boolean value) {

      wantAssertionsSigned_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool want_assertions_signed = 7 [json_name = "wantAssertionsSigned"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWantAssertionsSigned() {
      bitField0_ = (bitField0_ & ~0x00000040);
      wantAssertionsSigned_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.connections.GetSAMLMetadataResponse)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.connections.GetSAMLMetadataResponse)
  private static final com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse();
  }

  public static com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSAMLMetadataResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSAMLMetadataResponse>() {
    @java.lang.Override
    public GetSAMLMetadataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSAMLMetadataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSAMLMetadataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.connections.GetSAMLMetadataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

