// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/migrations/migrations.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.migrations;

/**
 * Protobuf enum {@code scalekit.v1.migrations.FSADataType}
 */
public enum FSADataType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FSA_DATA_TYPE_UNSPECIFIED = 0;</code>
   */
  FSA_DATA_TYPE_UNSPECIFIED(0),
  /**
   * <code>FSA_DATA_TYPE_CONNECTION = 1;</code>
   */
  FSA_DATA_TYPE_CONNECTION(1),
  /**
   * <code>FSA_DATA_TYPE_SESSION = 2;</code>
   */
  FSA_DATA_TYPE_SESSION(2),
  /**
   * <code>FSA_DATA_TYPE_USER_MANAGEMENT = 3;</code>
   */
  FSA_DATA_TYPE_USER_MANAGEMENT(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FSA_DATA_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int FSA_DATA_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>FSA_DATA_TYPE_CONNECTION = 1;</code>
   */
  public static final int FSA_DATA_TYPE_CONNECTION_VALUE = 1;
  /**
   * <code>FSA_DATA_TYPE_SESSION = 2;</code>
   */
  public static final int FSA_DATA_TYPE_SESSION_VALUE = 2;
  /**
   * <code>FSA_DATA_TYPE_USER_MANAGEMENT = 3;</code>
   */
  public static final int FSA_DATA_TYPE_USER_MANAGEMENT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FSADataType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FSADataType forNumber(int value) {
    switch (value) {
      case 0: return FSA_DATA_TYPE_UNSPECIFIED;
      case 1: return FSA_DATA_TYPE_CONNECTION;
      case 2: return FSA_DATA_TYPE_SESSION;
      case 3: return FSA_DATA_TYPE_USER_MANAGEMENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FSADataType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FSADataType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FSADataType>() {
          public FSADataType findValueByNumber(int number) {
            return FSADataType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.migrations.MigrationsProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final FSADataType[] VALUES = values();

  public static FSADataType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FSADataType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:scalekit.v1.migrations.FSADataType)
}

