// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/options/options.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.options;

/**
 * <pre>
 * AgentFieldOption controls a single field's visibility to the support agent.
 *
 * PRESENCE RULES — the generator reads this option with `proto.HasExtension`, not by
 * reading the zero value, so three states are distinguishable and they behave differently:
 *
 *   1. Option ABSENT              =&gt; field is EXPOSED. This is the default; most fields
 *                                    carry no annotation at all.
 *   2. `[(agent_field).expose = false]` =&gt; field is HIDDEN. This is the only way to hide a
 *                                    field: stripped from the request schema and dropped
 *                                    from the projected response.
 *   3. `[(agent_field).expose = true]`  =&gt; field is EXPOSED, explicitly. Semantically
 *                                    identical to state 1, but it records an acknowledged
 *                                    review decision, which is what satisfies the
 *                                    generator's guard on sensitive-looking field names
 *                                    (`*secret*`, `*token*`, `*password*`, `*private_key*`,
 *                                    `*credential*`). Those names fail the build unless
 *                                    annotated either way.
 *
 * Do NOT read state 1 as `expose: false`. An absent option and an explicit `expose: false`
 * are opposite outcomes, and `[(agent_field) = {}]` reads as state 2 because `expose`
 * defaults to false inside a present message.
 * </pre>
 *
 * Protobuf type {@code scalekit.v1.options.AgentFieldOption}
 */
public final class AgentFieldOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.options.AgentFieldOption)
    AgentFieldOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AgentFieldOption.newBuilder() to construct.
  private AgentFieldOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AgentFieldOption() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AgentFieldOption();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.options.OptionsProto.internal_static_scalekit_v1_options_AgentFieldOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.options.OptionsProto.internal_static_scalekit_v1_options_AgentFieldOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.class, com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.Builder.class);
  }

  public static final int EXPOSE_FIELD_NUMBER = 1;
  private boolean expose_ = false;
  /**
   * <pre>
   * Whether the agent sees this field. Only meaningful when the option is present; see the
   * presence rules on the message.
   * </pre>
   *
   * <code>bool expose = 1 [json_name = "expose"];</code>
   * @return The expose.
   */
  @java.lang.Override
  public boolean getExpose() {
    return expose_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (expose_ != false) {
      output.writeBool(1, expose_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (expose_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, expose_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.options.AgentFieldOption)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.options.AgentFieldOption other = (com.scalekit.grpc.scalekit.v1.options.AgentFieldOption) obj;

    if (getExpose()
        != other.getExpose()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPOSE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExpose());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.options.AgentFieldOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AgentFieldOption controls a single field's visibility to the support agent.
   *
   * PRESENCE RULES — the generator reads this option with `proto.HasExtension`, not by
   * reading the zero value, so three states are distinguishable and they behave differently:
   *
   *   1. Option ABSENT              =&gt; field is EXPOSED. This is the default; most fields
   *                                    carry no annotation at all.
   *   2. `[(agent_field).expose = false]` =&gt; field is HIDDEN. This is the only way to hide a
   *                                    field: stripped from the request schema and dropped
   *                                    from the projected response.
   *   3. `[(agent_field).expose = true]`  =&gt; field is EXPOSED, explicitly. Semantically
   *                                    identical to state 1, but it records an acknowledged
   *                                    review decision, which is what satisfies the
   *                                    generator's guard on sensitive-looking field names
   *                                    (`*secret*`, `*token*`, `*password*`, `*private_key*`,
   *                                    `*credential*`). Those names fail the build unless
   *                                    annotated either way.
   *
   * Do NOT read state 1 as `expose: false`. An absent option and an explicit `expose: false`
   * are opposite outcomes, and `[(agent_field) = {}]` reads as state 2 because `expose`
   * defaults to false inside a present message.
   * </pre>
   *
   * Protobuf type {@code scalekit.v1.options.AgentFieldOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.options.AgentFieldOption)
      com.scalekit.grpc.scalekit.v1.options.AgentFieldOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.options.OptionsProto.internal_static_scalekit_v1_options_AgentFieldOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.options.OptionsProto.internal_static_scalekit_v1_options_AgentFieldOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.class, com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      expose_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.options.OptionsProto.internal_static_scalekit_v1_options_AgentFieldOption_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.options.AgentFieldOption getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.options.AgentFieldOption build() {
      com.scalekit.grpc.scalekit.v1.options.AgentFieldOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.options.AgentFieldOption buildPartial() {
      com.scalekit.grpc.scalekit.v1.options.AgentFieldOption result = new com.scalekit.grpc.scalekit.v1.options.AgentFieldOption(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.options.AgentFieldOption result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.expose_ = expose_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.options.AgentFieldOption) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.options.AgentFieldOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.options.AgentFieldOption other) {
      if (other == com.scalekit.grpc.scalekit.v1.options.AgentFieldOption.getDefaultInstance()) return this;
      if (other.getExpose() != false) {
        setExpose(other.getExpose());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              expose_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean expose_ ;
    /**
     * <pre>
     * Whether the agent sees this field. Only meaningful when the option is present; see the
     * presence rules on the message.
     * </pre>
     *
     * <code>bool expose = 1 [json_name = "expose"];</code>
     * @return The expose.
     */
    @java.lang.Override
    public boolean getExpose() {
      return expose_;
    }
    /**
     * <pre>
     * Whether the agent sees this field. Only meaningful when the option is present; see the
     * presence rules on the message.
     * </pre>
     *
     * <code>bool expose = 1 [json_name = "expose"];</code>
     * @param value The expose to set.
     * @return This builder for chaining.
     */
    public Builder setExpose(boolean value) {

      expose_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether the agent sees this field. Only meaningful when the option is present; see the
     * presence rules on the message.
     * </pre>
     *
     * <code>bool expose = 1 [json_name = "expose"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExpose() {
      bitField0_ = (bitField0_ & ~0x00000001);
      expose_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.options.AgentFieldOption)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.options.AgentFieldOption)
  private static final com.scalekit.grpc.scalekit.v1.options.AgentFieldOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.options.AgentFieldOption();
  }

  public static com.scalekit.grpc.scalekit.v1.options.AgentFieldOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentFieldOption>
      PARSER = new com.google.protobuf.AbstractParser<AgentFieldOption>() {
    @java.lang.Override
    public AgentFieldOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentFieldOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentFieldOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.options.AgentFieldOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

