// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/providers/providers.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.providers;

public interface UpdateCustomProviderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:scalekit.v1.providers.UpdateCustomProvider)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string display_name = 1 [json_name = "displayName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>string display_name = 1 [json_name = "displayName", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>string description = 2 [json_name = "description", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2 [json_name = "description", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.google.protobuf.ListValue auth_patterns = 4 [json_name = "authPatterns", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the authPatterns field is set.
   */
  boolean hasAuthPatterns();
  /**
   * <code>.google.protobuf.ListValue auth_patterns = 4 [json_name = "authPatterns", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The authPatterns.
   */
  com.google.protobuf.ListValue getAuthPatterns();
  /**
   * <code>.google.protobuf.ListValue auth_patterns = 4 [json_name = "authPatterns", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  com.google.protobuf.ListValueOrBuilder getAuthPatternsOrBuilder();

  /**
   * <code>string proxy_url = 7 [json_name = "proxyUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The proxyUrl.
   */
  java.lang.String getProxyUrl();
  /**
   * <code>string proxy_url = 7 [json_name = "proxyUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for proxyUrl.
   */
  com.google.protobuf.ByteString
      getProxyUrlBytes();

  /**
   * <code>bool proxy_enabled = 8 [json_name = "proxyEnabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The proxyEnabled.
   */
  boolean getProxyEnabled();

  /**
   * <code>string icon_src = 9 [json_name = "iconSrc", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The iconSrc.
   */
  java.lang.String getIconSrc();
  /**
   * <code>string icon_src = 9 [json_name = "iconSrc", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for iconSrc.
   */
  com.google.protobuf.ByteString
      getIconSrcBytes();

  /**
   * <code>map&lt;string, string&gt; metadata = 10 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 10 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 10 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 10 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 10 [json_name = "metadata", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);
}
