// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/keys/keys.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.keys;

/**
 * <pre>
 * DEKKeyType represents the type of Data Encryption Key
 * </pre>
 *
 * Protobuf enum {@code scalekit.v1.keys.DEKKeyType}
 */
public enum DEKKeyType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default: ENVIRONMENT_KEY (envelope encryption)
   * </pre>
   *
   * <code>DEK_KEY_TYPE_UNSPECIFIED = 0;</code>
   */
  DEK_KEY_TYPE_UNSPECIFIED(0),
  /**
   * <code>ENVIRONMENT_KEY = 1;</code>
   */
  ENVIRONMENT_KEY(1),
  /**
   * <pre>
   * Bring Your Own Key - key_ref points to customer KMS
   * </pre>
   *
   * <code>BYOK = 2;</code>
   */
  BYOK(2),
  /**
   * <pre>
   * Scalekit-managed KMS key
   * </pre>
   *
   * <code>SCALEKIT_MANAGED_KEY = 3;</code>
   */
  SCALEKIT_MANAGED_KEY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default: ENVIRONMENT_KEY (envelope encryption)
   * </pre>
   *
   * <code>DEK_KEY_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int DEK_KEY_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ENVIRONMENT_KEY = 1;</code>
   */
  public static final int ENVIRONMENT_KEY_VALUE = 1;
  /**
   * <pre>
   * Bring Your Own Key - key_ref points to customer KMS
   * </pre>
   *
   * <code>BYOK = 2;</code>
   */
  public static final int BYOK_VALUE = 2;
  /**
   * <pre>
   * Scalekit-managed KMS key
   * </pre>
   *
   * <code>SCALEKIT_MANAGED_KEY = 3;</code>
   */
  public static final int SCALEKIT_MANAGED_KEY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DEKKeyType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DEKKeyType forNumber(int value) {
    switch (value) {
      case 0: return DEK_KEY_TYPE_UNSPECIFIED;
      case 1: return ENVIRONMENT_KEY;
      case 2: return BYOK;
      case 3: return SCALEKIT_MANAGED_KEY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DEKKeyType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DEKKeyType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DEKKeyType>() {
          public DEKKeyType findValueByNumber(int number) {
            return DEKKeyType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.keys.KeysProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final DEKKeyType[] VALUES = values();

  public static DEKKeyType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DEKKeyType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:scalekit.v1.keys.DEKKeyType)
}

