// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/organizations/organizations.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.organizations;

/**
 * Protobuf type {@code scalekit.v1.organizations.ApplicationSessionPolicySettings}
 */
public final class ApplicationSessionPolicySettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.organizations.ApplicationSessionPolicySettings)
    ApplicationSessionPolicySettingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ApplicationSessionPolicySettings.newBuilder() to construct.
  private ApplicationSessionPolicySettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ApplicationSessionPolicySettings() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApplicationSessionPolicySettings();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.organizations.OrganizationsProto.internal_static_scalekit_v1_organizations_ApplicationSessionPolicySettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.organizations.OrganizationsProto.internal_static_scalekit_v1_organizations_ApplicationSessionPolicySettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.class, com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.Builder.class);
  }

  public static final int ABSOLUTE_SESSION_TIMEOUT_FIELD_NUMBER = 1;
  private int absoluteSessionTimeout_ = 0;
  /**
   * <code>int32 absolute_session_timeout = 1 [json_name = "absoluteSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The absoluteSessionTimeout.
   */
  @java.lang.Override
  public int getAbsoluteSessionTimeout() {
    return absoluteSessionTimeout_;
  }

  public static final int IDLE_SESSION_TIMEOUT_ENABLED_FIELD_NUMBER = 2;
  private boolean idleSessionTimeoutEnabled_ = false;
  /**
   * <code>bool idle_session_timeout_enabled = 2 [json_name = "idleSessionTimeoutEnabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The idleSessionTimeoutEnabled.
   */
  @java.lang.Override
  public boolean getIdleSessionTimeoutEnabled() {
    return idleSessionTimeoutEnabled_;
  }

  public static final int IDLE_SESSION_TIMEOUT_FIELD_NUMBER = 3;
  private int idleSessionTimeout_ = 0;
  /**
   * <code>int32 idle_session_timeout = 3 [json_name = "idleSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The idleSessionTimeout.
   */
  @java.lang.Override
  public int getIdleSessionTimeout() {
    return idleSessionTimeout_;
  }

  public static final int ACCESS_TOKEN_EXPIRY_FIELD_NUMBER = 4;
  private int accessTokenExpiry_ = 0;
  /**
   * <code>int32 access_token_expiry = 4 [json_name = "accessTokenExpiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The accessTokenExpiry.
   */
  @java.lang.Override
  public int getAccessTokenExpiry() {
    return accessTokenExpiry_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (absoluteSessionTimeout_ != 0) {
      output.writeInt32(1, absoluteSessionTimeout_);
    }
    if (idleSessionTimeoutEnabled_ != false) {
      output.writeBool(2, idleSessionTimeoutEnabled_);
    }
    if (idleSessionTimeout_ != 0) {
      output.writeInt32(3, idleSessionTimeout_);
    }
    if (accessTokenExpiry_ != 0) {
      output.writeInt32(4, accessTokenExpiry_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (absoluteSessionTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, absoluteSessionTimeout_);
    }
    if (idleSessionTimeoutEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, idleSessionTimeoutEnabled_);
    }
    if (idleSessionTimeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, idleSessionTimeout_);
    }
    if (accessTokenExpiry_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, accessTokenExpiry_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings other = (com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings) obj;

    if (getAbsoluteSessionTimeout()
        != other.getAbsoluteSessionTimeout()) return false;
    if (getIdleSessionTimeoutEnabled()
        != other.getIdleSessionTimeoutEnabled()) return false;
    if (getIdleSessionTimeout()
        != other.getIdleSessionTimeout()) return false;
    if (getAccessTokenExpiry()
        != other.getAccessTokenExpiry()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ABSOLUTE_SESSION_TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getAbsoluteSessionTimeout();
    hash = (37 * hash) + IDLE_SESSION_TIMEOUT_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIdleSessionTimeoutEnabled());
    hash = (37 * hash) + IDLE_SESSION_TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getIdleSessionTimeout();
    hash = (37 * hash) + ACCESS_TOKEN_EXPIRY_FIELD_NUMBER;
    hash = (53 * hash) + getAccessTokenExpiry();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scalekit.v1.organizations.ApplicationSessionPolicySettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.organizations.ApplicationSessionPolicySettings)
      com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.organizations.OrganizationsProto.internal_static_scalekit_v1_organizations_ApplicationSessionPolicySettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.organizations.OrganizationsProto.internal_static_scalekit_v1_organizations_ApplicationSessionPolicySettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.class, com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      absoluteSessionTimeout_ = 0;
      idleSessionTimeoutEnabled_ = false;
      idleSessionTimeout_ = 0;
      accessTokenExpiry_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.organizations.OrganizationsProto.internal_static_scalekit_v1_organizations_ApplicationSessionPolicySettings_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings build() {
      com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings buildPartial() {
      com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings result = new com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.absoluteSessionTimeout_ = absoluteSessionTimeout_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idleSessionTimeoutEnabled_ = idleSessionTimeoutEnabled_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idleSessionTimeout_ = idleSessionTimeout_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accessTokenExpiry_ = accessTokenExpiry_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings other) {
      if (other == com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings.getDefaultInstance()) return this;
      if (other.getAbsoluteSessionTimeout() != 0) {
        setAbsoluteSessionTimeout(other.getAbsoluteSessionTimeout());
      }
      if (other.getIdleSessionTimeoutEnabled() != false) {
        setIdleSessionTimeoutEnabled(other.getIdleSessionTimeoutEnabled());
      }
      if (other.getIdleSessionTimeout() != 0) {
        setIdleSessionTimeout(other.getIdleSessionTimeout());
      }
      if (other.getAccessTokenExpiry() != 0) {
        setAccessTokenExpiry(other.getAccessTokenExpiry());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              absoluteSessionTimeout_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              idleSessionTimeoutEnabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              idleSessionTimeout_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              accessTokenExpiry_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int absoluteSessionTimeout_ ;
    /**
     * <code>int32 absolute_session_timeout = 1 [json_name = "absoluteSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The absoluteSessionTimeout.
     */
    @java.lang.Override
    public int getAbsoluteSessionTimeout() {
      return absoluteSessionTimeout_;
    }
    /**
     * <code>int32 absolute_session_timeout = 1 [json_name = "absoluteSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The absoluteSessionTimeout to set.
     * @return This builder for chaining.
     */
    public Builder setAbsoluteSessionTimeout(int value) {

      absoluteSessionTimeout_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 absolute_session_timeout = 1 [json_name = "absoluteSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAbsoluteSessionTimeout() {
      bitField0_ = (bitField0_ & ~0x00000001);
      absoluteSessionTimeout_ = 0;
      onChanged();
      return this;
    }

    private boolean idleSessionTimeoutEnabled_ ;
    /**
     * <code>bool idle_session_timeout_enabled = 2 [json_name = "idleSessionTimeoutEnabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The idleSessionTimeoutEnabled.
     */
    @java.lang.Override
    public boolean getIdleSessionTimeoutEnabled() {
      return idleSessionTimeoutEnabled_;
    }
    /**
     * <code>bool idle_session_timeout_enabled = 2 [json_name = "idleSessionTimeoutEnabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The idleSessionTimeoutEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIdleSessionTimeoutEnabled(boolean value) {

      idleSessionTimeoutEnabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool idle_session_timeout_enabled = 2 [json_name = "idleSessionTimeoutEnabled", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearIdleSessionTimeoutEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      idleSessionTimeoutEnabled_ = false;
      onChanged();
      return this;
    }

    private int idleSessionTimeout_ ;
    /**
     * <code>int32 idle_session_timeout = 3 [json_name = "idleSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The idleSessionTimeout.
     */
    @java.lang.Override
    public int getIdleSessionTimeout() {
      return idleSessionTimeout_;
    }
    /**
     * <code>int32 idle_session_timeout = 3 [json_name = "idleSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The idleSessionTimeout to set.
     * @return This builder for chaining.
     */
    public Builder setIdleSessionTimeout(int value) {

      idleSessionTimeout_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idle_session_timeout = 3 [json_name = "idleSessionTimeout", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearIdleSessionTimeout() {
      bitField0_ = (bitField0_ & ~0x00000004);
      idleSessionTimeout_ = 0;
      onChanged();
      return this;
    }

    private int accessTokenExpiry_ ;
    /**
     * <code>int32 access_token_expiry = 4 [json_name = "accessTokenExpiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The accessTokenExpiry.
     */
    @java.lang.Override
    public int getAccessTokenExpiry() {
      return accessTokenExpiry_;
    }
    /**
     * <code>int32 access_token_expiry = 4 [json_name = "accessTokenExpiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The accessTokenExpiry to set.
     * @return This builder for chaining.
     */
    public Builder setAccessTokenExpiry(int value) {

      accessTokenExpiry_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 access_token_expiry = 4 [json_name = "accessTokenExpiry", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessTokenExpiry() {
      bitField0_ = (bitField0_ & ~0x00000008);
      accessTokenExpiry_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.organizations.ApplicationSessionPolicySettings)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.organizations.ApplicationSessionPolicySettings)
  private static final com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings();
  }

  public static com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationSessionPolicySettings>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationSessionPolicySettings>() {
    @java.lang.Override
    public ApplicationSessionPolicySettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ApplicationSessionPolicySettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplicationSessionPolicySettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.organizations.ApplicationSessionPolicySettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

