// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scalekit/v1/interceptors/interceptors.proto

// Protobuf Java Version: 3.25.3
package com.scalekit.grpc.scalekit.v1.interceptors;

/**
 * Protobuf type {@code scalekit.v1.interceptors.CreateInterceptor}
 */
public final class CreateInterceptor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:scalekit.v1.interceptors.CreateInterceptor)
    CreateInterceptorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateInterceptor.newBuilder() to construct.
  private CreateInterceptor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateInterceptor() {
    displayName_ = "";
    description_ = "";
    triggerPoint_ = 0;
    interceptorType_ = 0;
    apiUrl_ = "";
    failurePolicy_ = 0;
    requestTemplate_ = "";
    responseTemplate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateInterceptor();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.scalekit.grpc.scalekit.v1.interceptors.InterceptorsProto.internal_static_scalekit_v1_interceptors_CreateInterceptor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.scalekit.grpc.scalekit.v1.interceptors.InterceptorsProto.internal_static_scalekit_v1_interceptors_CreateInterceptor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.class, com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.Builder.class);
  }

  private int bitField0_;
  public static final int DISPLAY_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object displayName_ = "";
  /**
   * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRIGGER_POINT_FIELD_NUMBER = 3;
  private int triggerPoint_ = 0;
  /**
   * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for triggerPoint.
   */
  @java.lang.Override public int getTriggerPointValue() {
    return triggerPoint_;
  }
  /**
   * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
   * @return The triggerPoint.
   */
  @java.lang.Override public com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint getTriggerPoint() {
    com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint result = com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.forNumber(triggerPoint_);
    return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.UNRECOGNIZED : result;
  }

  public static final int INTERCEPTOR_TYPE_FIELD_NUMBER = 4;
  private int interceptorType_ = 0;
  /**
   * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the interceptorType field is set.
   */
  @java.lang.Override public boolean hasInterceptorType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The enum numeric value on the wire for interceptorType.
   */
  @java.lang.Override public int getInterceptorTypeValue() {
    return interceptorType_;
  }
  /**
   * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The interceptorType.
   */
  @java.lang.Override public com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType getInterceptorType() {
    com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType result = com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType.forNumber(interceptorType_);
    return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType.UNRECOGNIZED : result;
  }

  public static final int API_URL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object apiUrl_ = "";
  /**
   * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the apiUrl field is set.
   */
  @java.lang.Override
  public boolean hasApiUrl() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The apiUrl.
   */
  @java.lang.Override
  public java.lang.String getApiUrl() {
    java.lang.Object ref = apiUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiUrl_ = s;
      return s;
    }
  }
  /**
   * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for apiUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiUrlBytes() {
    java.lang.Object ref = apiUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_FIELD_NUMBER = 6;
  private com.scalekit.grpc.scalekit.v1.interceptors.Config config_;
  /**
   * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The config.
   */
  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.interceptors.Config getConfig() {
    return config_ == null ? com.scalekit.grpc.scalekit.v1.interceptors.Config.getDefaultInstance() : config_;
  }
  /**
   * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   */
  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.interceptors.ConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? com.scalekit.grpc.scalekit.v1.interceptors.Config.getDefaultInstance() : config_;
  }

  public static final int TIMEOUT_MS_FIELD_NUMBER = 7;
  private long timeoutMs_ = 0L;
  /**
   * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the timeoutMs field is set.
   */
  @java.lang.Override
  public boolean hasTimeoutMs() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The timeoutMs.
   */
  @java.lang.Override
  public long getTimeoutMs() {
    return timeoutMs_;
  }

  public static final int FAILURE_POLICY_FIELD_NUMBER = 8;
  private int failurePolicy_ = 0;
  /**
   * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the failurePolicy field is set.
   */
  @java.lang.Override public boolean hasFailurePolicy() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The enum numeric value on the wire for failurePolicy.
   */
  @java.lang.Override public int getFailurePolicyValue() {
    return failurePolicy_;
  }
  /**
   * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The failurePolicy.
   */
  @java.lang.Override public com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy getFailurePolicy() {
    com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy result = com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy.forNumber(failurePolicy_);
    return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy.UNRECOGNIZED : result;
  }

  public static final int REQUEST_TEMPLATE_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestTemplate_ = "";
  /**
   * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the requestTemplate field is set.
   */
  @java.lang.Override
  public boolean hasRequestTemplate() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The requestTemplate.
   */
  @java.lang.Override
  public java.lang.String getRequestTemplate() {
    java.lang.Object ref = requestTemplate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestTemplate_ = s;
      return s;
    }
  }
  /**
   * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for requestTemplate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestTemplateBytes() {
    java.lang.Object ref = requestTemplate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestTemplate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_TEMPLATE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responseTemplate_ = "";
  /**
   * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return Whether the responseTemplate field is set.
   */
  @java.lang.Override
  public boolean hasResponseTemplate() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The responseTemplate.
   */
  @java.lang.Override
  public java.lang.String getResponseTemplate() {
    java.lang.Object ref = responseTemplate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseTemplate_ = s;
      return s;
    }
  }
  /**
   * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for responseTemplate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseTemplateBytes() {
    java.lang.Object ref = responseTemplate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseTemplate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
    }
    if (triggerPoint_ != com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.TRIGGER_POINT_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, triggerPoint_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(4, interceptorType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, apiUrl_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getConfig());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeUInt64(7, timeoutMs_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(8, failurePolicy_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, requestTemplate_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, responseTemplate_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(displayName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, displayName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
    }
    if (triggerPoint_ != com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.TRIGGER_POINT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, triggerPoint_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, interceptorType_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, apiUrl_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getConfig());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, timeoutMs_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, failurePolicy_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, requestTemplate_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, responseTemplate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor)) {
      return super.equals(obj);
    }
    com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor other = (com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor) obj;

    if (!getDisplayName()
        .equals(other.getDisplayName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (triggerPoint_ != other.triggerPoint_) return false;
    if (hasInterceptorType() != other.hasInterceptorType()) return false;
    if (hasInterceptorType()) {
      if (interceptorType_ != other.interceptorType_) return false;
    }
    if (hasApiUrl() != other.hasApiUrl()) return false;
    if (hasApiUrl()) {
      if (!getApiUrl()
          .equals(other.getApiUrl())) return false;
    }
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (hasTimeoutMs() != other.hasTimeoutMs()) return false;
    if (hasTimeoutMs()) {
      if (getTimeoutMs()
          != other.getTimeoutMs()) return false;
    }
    if (hasFailurePolicy() != other.hasFailurePolicy()) return false;
    if (hasFailurePolicy()) {
      if (failurePolicy_ != other.failurePolicy_) return false;
    }
    if (hasRequestTemplate() != other.hasRequestTemplate()) return false;
    if (hasRequestTemplate()) {
      if (!getRequestTemplate()
          .equals(other.getRequestTemplate())) return false;
    }
    if (hasResponseTemplate() != other.hasResponseTemplate()) return false;
    if (hasResponseTemplate()) {
      if (!getResponseTemplate()
          .equals(other.getResponseTemplate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAY_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + TRIGGER_POINT_FIELD_NUMBER;
    hash = (53 * hash) + triggerPoint_;
    if (hasInterceptorType()) {
      hash = (37 * hash) + INTERCEPTOR_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + interceptorType_;
    }
    if (hasApiUrl()) {
      hash = (37 * hash) + API_URL_FIELD_NUMBER;
      hash = (53 * hash) + getApiUrl().hashCode();
    }
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    if (hasTimeoutMs()) {
      hash = (37 * hash) + TIMEOUT_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeoutMs());
    }
    if (hasFailurePolicy()) {
      hash = (37 * hash) + FAILURE_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + failurePolicy_;
    }
    if (hasRequestTemplate()) {
      hash = (37 * hash) + REQUEST_TEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestTemplate().hashCode();
    }
    if (hasResponseTemplate()) {
      hash = (37 * hash) + RESPONSE_TEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseTemplate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code scalekit.v1.interceptors.CreateInterceptor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:scalekit.v1.interceptors.CreateInterceptor)
      com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.scalekit.grpc.scalekit.v1.interceptors.InterceptorsProto.internal_static_scalekit_v1_interceptors_CreateInterceptor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.scalekit.grpc.scalekit.v1.interceptors.InterceptorsProto.internal_static_scalekit_v1_interceptors_CreateInterceptor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.class, com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.Builder.class);
    }

    // Construct using com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      displayName_ = "";
      description_ = "";
      triggerPoint_ = 0;
      interceptorType_ = 0;
      apiUrl_ = "";
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      timeoutMs_ = 0L;
      failurePolicy_ = 0;
      requestTemplate_ = "";
      responseTemplate_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.scalekit.grpc.scalekit.v1.interceptors.InterceptorsProto.internal_static_scalekit_v1_interceptors_CreateInterceptor_descriptor;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor getDefaultInstanceForType() {
      return com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.getDefaultInstance();
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor build() {
      com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor buildPartial() {
      com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor result = new com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.displayName_ = displayName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.triggerPoint_ = triggerPoint_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.interceptorType_ = interceptorType_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.apiUrl_ = apiUrl_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timeoutMs_ = timeoutMs_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.failurePolicy_ = failurePolicy_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.requestTemplate_ = requestTemplate_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.responseTemplate_ = responseTemplate_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor) {
        return mergeFrom((com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor other) {
      if (other == com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor.getDefaultInstance()) return this;
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.triggerPoint_ != 0) {
        setTriggerPointValue(other.getTriggerPointValue());
      }
      if (other.hasInterceptorType()) {
        setInterceptorType(other.getInterceptorType());
      }
      if (other.hasApiUrl()) {
        apiUrl_ = other.apiUrl_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      if (other.hasTimeoutMs()) {
        setTimeoutMs(other.getTimeoutMs());
      }
      if (other.hasFailurePolicy()) {
        setFailurePolicy(other.getFailurePolicy());
      }
      if (other.hasRequestTemplate()) {
        requestTemplate_ = other.requestTemplate_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.hasResponseTemplate()) {
        responseTemplate_ = other.responseTemplate_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              displayName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              triggerPoint_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              interceptorType_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              apiUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timeoutMs_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              failurePolicy_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              requestTemplate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              responseTemplate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object displayName_ = "";
    /**
     * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
     * @return The displayName.
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
     * @return The bytes for displayName.
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      displayName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      displayName_ = getDefaultInstance().getDisplayName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string display_name = 1 [json_name = "displayName", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      displayName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 2 [json_name = "description", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int triggerPoint_ = 0;
    /**
     * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for triggerPoint.
     */
    @java.lang.Override public int getTriggerPointValue() {
      return triggerPoint_;
    }
    /**
     * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for triggerPoint to set.
     * @return This builder for chaining.
     */
    public Builder setTriggerPointValue(int value) {
      triggerPoint_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
     * @return The triggerPoint.
     */
    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint getTriggerPoint() {
      com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint result = com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.forNumber(triggerPoint_);
      return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint.UNRECOGNIZED : result;
    }
    /**
     * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
     * @param value The triggerPoint to set.
     * @return This builder for chaining.
     */
    public Builder setTriggerPoint(com.scalekit.grpc.scalekit.v1.interceptors.TriggerPoint value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      triggerPoint_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.scalekit.v1.interceptors.TriggerPoint trigger_point = 3 [json_name = "triggerPoint", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTriggerPoint() {
      bitField0_ = (bitField0_ & ~0x00000004);
      triggerPoint_ = 0;
      onChanged();
      return this;
    }

    private int interceptorType_ = 0;
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the interceptorType field is set.
     */
    @java.lang.Override public boolean hasInterceptorType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The enum numeric value on the wire for interceptorType.
     */
    @java.lang.Override public int getInterceptorTypeValue() {
      return interceptorType_;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The enum numeric value on the wire for interceptorType to set.
     * @return This builder for chaining.
     */
    public Builder setInterceptorTypeValue(int value) {
      interceptorType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The interceptorType.
     */
    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType getInterceptorType() {
      com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType result = com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType.forNumber(interceptorType_);
      return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The interceptorType to set.
     * @return This builder for chaining.
     */
    public Builder setInterceptorType(com.scalekit.grpc.scalekit.v1.interceptors.InterceptorType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      interceptorType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.InterceptorType interceptor_type = 4 [json_name = "interceptorType", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearInterceptorType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      interceptorType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object apiUrl_ = "";
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the apiUrl field is set.
     */
    public boolean hasApiUrl() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The apiUrl.
     */
    public java.lang.String getApiUrl() {
      java.lang.Object ref = apiUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for apiUrl.
     */
    public com.google.protobuf.ByteString
        getApiUrlBytes() {
      java.lang.Object ref = apiUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The apiUrl to set.
     * @return This builder for chaining.
     */
    public Builder setApiUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      apiUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearApiUrl() {
      apiUrl_ = getDefaultInstance().getApiUrl();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string api_url = 5 [json_name = "apiUrl", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for apiUrl to set.
     * @return This builder for chaining.
     */
    public Builder setApiUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      apiUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.scalekit.grpc.scalekit.v1.interceptors.Config config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalekit.grpc.scalekit.v1.interceptors.Config, com.scalekit.grpc.scalekit.v1.interceptors.Config.Builder, com.scalekit.grpc.scalekit.v1.interceptors.ConfigOrBuilder> configBuilder_;
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The config.
     */
    public com.scalekit.grpc.scalekit.v1.interceptors.Config getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? com.scalekit.grpc.scalekit.v1.interceptors.Config.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setConfig(com.scalekit.grpc.scalekit.v1.interceptors.Config value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder setConfig(
        com.scalekit.grpc.scalekit.v1.interceptors.Config.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder mergeConfig(com.scalekit.grpc.scalekit.v1.interceptors.Config value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          config_ != null &&
          config_ != com.scalekit.grpc.scalekit.v1.interceptors.Config.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      if (config_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000020);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.scalekit.grpc.scalekit.v1.interceptors.Config.Builder getConfigBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    public com.scalekit.grpc.scalekit.v1.interceptors.ConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            com.scalekit.grpc.scalekit.v1.interceptors.Config.getDefaultInstance() : config_;
      }
    }
    /**
     * <code>optional .scalekit.v1.interceptors.Config config = 6 [json_name = "config", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.scalekit.grpc.scalekit.v1.interceptors.Config, com.scalekit.grpc.scalekit.v1.interceptors.Config.Builder, com.scalekit.grpc.scalekit.v1.interceptors.ConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.scalekit.grpc.scalekit.v1.interceptors.Config, com.scalekit.grpc.scalekit.v1.interceptors.Config.Builder, com.scalekit.grpc.scalekit.v1.interceptors.ConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    private long timeoutMs_ ;
    /**
     * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the timeoutMs field is set.
     */
    @java.lang.Override
    public boolean hasTimeoutMs() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The timeoutMs.
     */
    @java.lang.Override
    public long getTimeoutMs() {
      return timeoutMs_;
    }
    /**
     * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The timeoutMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutMs(long value) {

      timeoutMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 timeout_ms = 7 [json_name = "timeoutMs", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timeoutMs_ = 0L;
      onChanged();
      return this;
    }

    private int failurePolicy_ = 0;
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the failurePolicy field is set.
     */
    @java.lang.Override public boolean hasFailurePolicy() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The enum numeric value on the wire for failurePolicy.
     */
    @java.lang.Override public int getFailurePolicyValue() {
      return failurePolicy_;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The enum numeric value on the wire for failurePolicy to set.
     * @return This builder for chaining.
     */
    public Builder setFailurePolicyValue(int value) {
      failurePolicy_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The failurePolicy.
     */
    @java.lang.Override
    public com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy getFailurePolicy() {
      com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy result = com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy.forNumber(failurePolicy_);
      return result == null ? com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The failurePolicy to set.
     * @return This builder for chaining.
     */
    public Builder setFailurePolicy(com.scalekit.grpc.scalekit.v1.interceptors.FailurePolicy value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      failurePolicy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .scalekit.v1.interceptors.FailurePolicy failure_policy = 8 [json_name = "failurePolicy", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearFailurePolicy() {
      bitField0_ = (bitField0_ & ~0x00000080);
      failurePolicy_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object requestTemplate_ = "";
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the requestTemplate field is set.
     */
    public boolean hasRequestTemplate() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The requestTemplate.
     */
    public java.lang.String getRequestTemplate() {
      java.lang.Object ref = requestTemplate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestTemplate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for requestTemplate.
     */
    public com.google.protobuf.ByteString
        getRequestTemplateBytes() {
      java.lang.Object ref = requestTemplate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestTemplate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The requestTemplate to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTemplate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestTemplate_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestTemplate() {
      requestTemplate_ = getDefaultInstance().getRequestTemplate();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string request_template = 9 [json_name = "requestTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for requestTemplate to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTemplateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestTemplate_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object responseTemplate_ = "";
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return Whether the responseTemplate field is set.
     */
    public boolean hasResponseTemplate() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The responseTemplate.
     */
    public java.lang.String getResponseTemplate() {
      java.lang.Object ref = responseTemplate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseTemplate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for responseTemplate.
     */
    public com.google.protobuf.ByteString
        getResponseTemplateBytes() {
      java.lang.Object ref = responseTemplate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseTemplate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The responseTemplate to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTemplate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responseTemplate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTemplate() {
      responseTemplate_ = getDefaultInstance().getResponseTemplate();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>optional string response_template = 10 [json_name = "responseTemplate", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for responseTemplate to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTemplateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseTemplate_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:scalekit.v1.interceptors.CreateInterceptor)
  }

  // @@protoc_insertion_point(class_scope:scalekit.v1.interceptors.CreateInterceptor)
  private static final com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor();
  }

  public static com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateInterceptor>
      PARSER = new com.google.protobuf.AbstractParser<CreateInterceptor>() {
    @java.lang.Override
    public CreateInterceptor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateInterceptor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateInterceptor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.scalekit.grpc.scalekit.v1.interceptors.CreateInterceptor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

